<?php $this->layout('layouts/admin'); ?>

<?php $this->section('content') ?>

    <div class="homebox">
        <div class="body">
            <ol class="breadcrumb">
                <li><a href="/admin">Admin</a></li>
                <li class="active">Articles</li>
            </ol>

            <form action="/admin/articles" method="post">
                <div class="buttons">
                    <div class="col-md-6 hidden-s hidden-xs">
                        &nbsp;
                    </div>
                    <div class="col-md-6 text-right">
                        <button type="submit" class="btn btn-default">New article</button>
                    </div>
                </div>
            </form>

            <table class="table table-striped">
                <tr>
                    <th><a href="#">Title</a>
</th>
                    <th><a href="#">Type</a></th>
                    <th><a href="#">Created</a> <i class="fa fa-caret-down" aria-hidden="true"></i></th>
                </tr>
                <?php foreach ($this->articles as $article): ?>
                    <tr>
                        <td><a href="/admin/articles/<?= $article->id ?>"><?= $article->title ?></a></td>
                        <td><?= $article->type ?></td>
                        <td><?= $article->created_at ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>

            <?= $this->insert('blog/partials/pagination_links') ?>
        </div>
    </div>
<?php $this->replace() ?>
