<?php $this->layout('layouts/admin'); ?>

<?php $this->section('content') ?>

    <div class="homebox">
        <div class="body">
            <ol class="breadcrumb">
                <li><a href="/admin">Admin</a></li>
                <li class="active">Articles</li>
            </ol>

            <form action="/admin/articles" method="post">
                <button type="submit" class="btn btn-default">New article</button>
            </form>

            <table class="table table-striped">
                <tr>
                    <th>Title</th>
                    <th>Type</th>
                    <th>Published</th>
                </tr>
                <?php foreach ($this->articles as $article): ?>
                    <tr>
                        <td><a href="/admin/articles/<?= $article->id ?>"><?= $article->title ?></a></td>
                        <td><?= $article->type ?></td>
                        <td><?= $article->published_at ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>

            <?= $this->insert('blog/partials/pagination_links') ?>
        </div>
    </div>
<?php $this->replace() ?>
