<?php $this->layout('layouts/admin'); ?>

<?php $this->section('content') ?>
    <ol class="breadcrumb">
        <li><a href="/admin">Admin</a></li>
        <li><a href="/admin/articles">Articles</a></li>
        <li class="active"><?= $this->article->title ?></li>
    </ol>

    <div class="buttons">
        <div class="col-md-6">

        </div>

        <div class="col-md-6 text-right">
            <a href="/admin/articles/<?= $this->article->id ?>/edit" class="btn btn-default">Edit</a>

            <form id="deleteUser" method="POST" action="/admin/articles/<?= $this->article->id ?>">
                <input type="hidden" name="_METHOD" value="DELETE">
                <button type="submit" class="btn btn-default">Delete</button>
            </form>

            <?php if($this->currentUser and ($this->currentUser->isAdmin() or $this->currentUser->isEditor())): ?>
                <?php if($this->article->status == 1): ?>
                    <form method="POST" action="/admin/articles/{{ $this->article->id }}">
                        <input type="hidden" name="_METHOD" value="PUT">
                        <button type="submit" name="status" value="2" class="btn btn-primary">Approve</button>
                    </form>
                <?php else: ?>
                    <form method="POST" action="/admin/articles/{{ $this->article->id }}">
                        <input type="hidden" name="_METHOD" value="PUT">
                        <button type="submit" name="status" value="1" class="btn btn-default">Unapprove</button>
                    </form>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>

    <table class="table table-striped">
        <tr>
            <th width="20%">Title</th>
            <td><?= $this->article->title ?></td>
        </tr>
        <tr>
            <th>Slug</th>
            <td><?= $this->article->slug ?></td>
        </tr>
        <tr>
            <th>Content</th>
            <td><?= $this->article->content ?></td>
        </tr>
        <tr>
            <th>Tags</th>
            <td>
                <?php if ($this->article->tags): ?>
                    <ul class="tags">
                        <?php foreach ($this->article->tags as $tag): ?>
                            <li><span><?= $tag->name ?></span></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th>Photos</th>
            <td>
                <?php if ($this->article->photos): ?>
                    <div class="photos">
                        <?php foreach ($this->article->photos as $photo): ?>
                            <img src="/photos<?= $photo->getCachedPath('x100') ?>" class="photo">
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>
        <tr>
            <th>Type</th>
            <td><?= $this->article->type ?></td>
        </tr>
        <tr>
            <th>Status</th>
            <td><?= $this->article->status ?></td>
        </tr>
        <tr>
            <th>Data created</th>
            <td><?= $this->article->created_at ?></td>
        </tr>
    </table>
<?php $this->replace() ?>
