<?php $this->layout('layouts/main'); ?>

<?php $this->section('content') ?>
    <div class="row">
        <div class="col-md-8">
            <div class="homebox">
                <div class="col-md-3 image">
                    <img src="/photos/201602/03/195/300x.jpg" class="img-responsive">
                </div>
                <div class="col-md-9 body">
                    <h2>Shungs</h2>
                    <p>Slim framework blah blah blah</p>
                    <p class="small">Written by {{ 'article.author.name' }} | {{ 'article.created_at' }}</p>
                </div>
            </div>

            <div class="homebox">
                <div class="col-md-12 body">
                    <h2>Earth parade</h2>
                    <p>Slim framework blah blah blah</p>
                    <p class="small">Written by {{ 'article.author.name' }} | {{ 'article.created_at' }}</p>
                </div>
            </div>

            <div class="homebox">
                <div class="col-md-3 image">
                    <img src="/photos/201602/03/195/300x.jpg" class="img-responsive">
                </div>
                <div class="col-md-9 body">
                    <h2>Cool kids in Vietnam</h2>
                    <p>Slim framework blah blah blah</p>
                    <p class="small">Written by {{ 'article.author.name' }} | {{ 'article.created_at' }}</p>
                </div>
            </div>

            <div class="homebox">
                <div class="col-md-3 image">
                    <img src="/photos/201602/03/195/300x.jpg" class="img-responsive">
                </div>
                <div class="col-md-9 body">
                    <h2>Waaaa office!</h2>
                    <p>Slim framework blah blah blah</p>
                    <p class="small">Written by {{ 'article.author.name' }} | {{ 'article.created_at' }}</p>
                </div>
            </div>

            <div class="homebox">
                <div class="col-md-3 image">
                    <img src="/photos/201602/03/195/300x.jpg" class="img-responsive">
                </div>
                <div class="col-md-9 body">
                    <h2>Cool kids in Vietnam</h2>
                    <p>Slim framework blah blah blah</p>
                    <p class="small">Written by {{ 'article.author.name' }} | {{ 'article.created_at' }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="homebox">
                <div class="col-md-12 body">
            		<form method="get" action="/">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button"><i class="glyphicon glyphicon-search"></i>&nbsp;</button>
                            </span>
                        </div>
            		</form>
                </div>
            </div>

            <div class="homebox">
                <div class="col-md-12 body">
                    <h3>Tags</h3>

                    <ul class="tags">
                        <li><a href="/tag">Tag</a></li>
                    </ul>
                </div>
            </div>

            <div class="homebox">
                <div class="col-md-12 body">
                    <h3>Featured</h3>

                    <ol class="featured">
                        <li><a href="#">A Bootstrap/LESS work-flow</a></li>
                        <li><a href="#">Deploying with Git</a></li>
                        <li><a href="#">Karaoke on Rails!</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
<?php $this->replace() ?>
