<?php $this->layout('layouts/main'); ?>

<?php $this->section('content') ?>
    <h1>Register</h1>

    <div class="col-sm-6 col-sm-offset-3 sso-register">
        <div class="row">
        	<div class="col-xs-12">
                <div class="well">
                    <form method="post" action="/auth/register">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="first_name" class="sr-only">First name</label>
                                    <input type="text" class="form-control" name="first_name" placeholder="First name" value="<?=$this->e($params['first_name'])?>">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="last_name" class="sr-only">Last name</label>
                                    <input type="text" class="form-control" name="last_name" placeholder="Last name" value="<?=$this->e($params['last_name'])?>">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input type="text" class="form-control" name="email" placeholder="Email" value="<?=$this->e($params['email'])?>">
                        </div>

                        <div class="form-group">
                            <label for="password" class="sr-only">Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Password" value="">
                        </div>

                        <label class="checkbox-inline agreement">
                            <input name="agreement" type="checkbox"> I have read the terms &amp; conditions.
                        </label>

                        <input type="text" class="more_info" name="more_info" value="" style="position: absolute; left: -9999px">

                        <?= $this->insert('partials/csrf_token') ?>

                        <hr>

                        <div class="row">
                            <div class="col-sm-6">
                                <button type="submit" class="btn btn-lg btn-block btn-primary">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php $this->replace() ?>
